'use client'

import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

interface Digest {
  id: string
  week_start: string
  week_end: string
  post_count: number
  digest_content: string
  created_at: string
}

export default function DigestView() {
  const params = useParams()
  const [digest, setDigest] = useState<Digest | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    loadDigest()
  }, [params.id])

  async function loadDigest() {
    const { data, error } = await supabase
      .from('weekly_digests')
      .select('*')
      .eq('id', params.id)
      .single()

    if (error) {
      setError('Digest not found')
    } else {
      setDigest(data)
    }
    setLoading(false)
  }

  function formatDate(dateString: string) {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    })
  }

  function renderMarkdown(content: string) {
    return content
      .replace(/^## (.*$)/gim, '<h2 class="text-2xl font-bold mt-8 mb-4 text-gray-900">$1</h2>')
      .replace(/^### (.*$)/gim, '<h3 class="text-xl font-semibold mt-6 mb-3 text-gray-800">$1</h3>')
      .replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/gim, '<em>$1</em>')
      .replace(/\[([^\]]+)\]\(([^)]+)\)/gim, '<a href="$2" class="text-blue-600 hover:underline" target="_blank" rel="noopener">$1</a>')
      .replace(/^- (.*$)/gim, '<li class="ml-4">$1</li>')
      .replace(/\n\n/gim, '</p><p class="mb-4">')
      .replace(/\n/gim, '<br>')
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-gray-500">Loading digest...</div>
      </div>
    )
  }

  if (error || !digest) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="text-4xl mb-4">😕</div>
          <h1 className="text-xl font-semibold text-gray-900 mb-2">Digest not found</h1>
          <p className="text-gray-600 mb-4">This digest may have been deleted or doesn't exist.</p>
          <a href="/dashboard" className="text-blue-600 hover:underline">
            ← Back to Dashboard
          </a>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-white border-b">
        <div className="max-w-3xl mx-auto px-6 py-6">
          <div className="flex items-center justify-between">
            <a href="/dashboard" className="text-gray-600 hover:text-gray-900">
              ← Dashboard
            </a>
            <a href="/" className="text-2xl font-bold text-gray-900">☕ Steep</a>
            <div className="w-20"></div>
          </div>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-6 py-12">
        <div className="bg-white rounded-xl shadow-sm p-8">
          <div className="text-center mb-8 pb-8 border-b">
            <div className="text-4xl mb-4">☕</div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Your Weekly Steep</h1>
            <p className="text-gray-600">
              {formatDate(digest.week_start)} — {formatDate(digest.week_end)}
            </p>
            <p className="text-sm text-gray-500 mt-2">
              {digest.post_count} posts brewed
            </p>
          </div>

          <div 
            className="prose prose-lg max-w-none"
            dangerouslySetInnerHTML={{ __html: renderMarkdown(digest.digest_content) }}
          />

          <div className="mt-12 pt-8 border-t text-center">
            <p className="text-gray-500 text-sm mb-4">
              Generated by Steep on {formatDate(digest.created_at)}
            </p>
            <a 
              href="/dashboard" 
              className="inline-block bg-gray-900 text-white px-6 py-2 rounded-lg font-semibold hover:bg-gray-800 transition"
            >
              View All Posts →
            </a>
          </div>
        </div>
      </div>
    </div>
  )
}
